# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Jd5PdfxAhVki_x8ufwod83tyic0pIJI
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import warnings
import io
warnings.filterwarnings('ignore')

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import pickle
import os

#
def crear_features_regulares(df, lags=7):
    df_copy = df.copy()
    for col in ['CLORO']:
        if col == 'CLORO':
            for i in range(1, lags + 1):
                df_copy[f'{col.lower()}_lag_{i}'] = df_copy[col].shift(i)
        else:
            for i in range(1, 4):
                df_copy[f'{col.lower()}_lag_{i}'] = df_copy[col].shift(i)
    for window_size in [2, 3, 4, 5, 6, 7]:
        df_copy[f'cloro_media_{window_size}d'] = df_copy['CLORO'].rolling(window=f'{window_size}D').mean().shift(1)
        df_copy[f'cloro_std_{window_size}d'] = df_copy['CLORO'].rolling(window=f'{window_size}D').std().shift(1)
        df_copy[f'cloro_min_{window_size}d'] = df_copy['CLORO'].rolling(window=f'{window_size}D').min().shift(1)
        df_copy[f'cloro_max_{window_size}d'] = df_copy['CLORO'].rolling(window=f'{window_size}D').max().shift(1)
    df_copy['cloro_diff_1'] = df_copy['CLORO'].diff(1)
    df_copy['cloro_diff_7'] = df_copy['CLORO'].diff(7)
    df_copy['dia_semana'] = df_copy.index.dayofweek
    df_copy['dia_mes'] = df_copy.index.day
    df_copy['mes'] = df_copy.index.month
    df_copy['es_fin_semana'] = (df_copy.index.dayofweek >= 5).astype(int)
    df_copy['sin_semana'] = np.sin(2 * np.pi * df_copy['dia_semana'] / 7)
    df_copy['cos_semana'] = np.cos(2 * np.pi * df_copy['dia_semana'] / 7)
    return df_copy

def ejecutar_analisis(df, test_size=0.2):
    """Versión ligera para la app (sin SHAP para no cargar la web)"""
    try:
        from tabicl import TabICLRegressor
    except ImportError:
        st.error("TabICL no está instalado. Ejecuta: pip install tabicl")
        return None

    df = df.copy()
    df['FECHA'] = pd.to_datetime(df['FECHA'])
    df = df.sort_values('FECHA')
    df_agg = df.groupby('FECHA')[['CLORO']].mean().reset_index()
    df_agg = df_agg.set_index('FECHA').asfreq('D')
    df_interp = df_agg.interpolate(method='linear').dropna()
    df_feat = crear_features_regulares(df_interp, lags=7).dropna()

    feature_cols = [c for c in df_feat.columns if c not in ['CLORO',]]
    X = df_feat[feature_cols]
    y = df_feat['CLORO']
    fechas = df_feat.index

    n_train = int(len(fechas) * (1 - test_size))
    X_train, X_test = X.iloc[:n_train], X.iloc[n_train:]
    y_train, y_test = y.iloc[:n_train], y.iloc[n_train:]
    fechas_test = fechas[n_train:]

    modelo = TabICLRegressor(random_state=42)
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Figura 1: Real vs Predicción
    fig, ax = plt.subplots(figsize=(10, 4), dpi=150)
    ax.plot(fechas_test, y_test, color='#2d2d2d', linewidth=1.6, label='Real', marker='.', markersize=3)
    ax.plot(fechas_test, y_pred, color='#27ae60', linewidth=1.8, linestyle='--', label='Predicción')
    ax.set_ylabel('Cloro libre (mg/L)')
    ax.set_xlabel('Fecha')
    ax.legend()
    ax.grid(alpha=0.3)
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
    plt.xticks(rotation=20)
    plt.tight_layout()

    return {
        'figura': fig,
        'metricas': {'RMSE': rmse, 'MAE': mae, 'R2': r2},
        'y_test': y_test,
        'y_pred': y_pred,
        'fechas_test': fechas_test,
        'modelo': modelo
    }

############## INTERFAZ DE STREAMLIT ##########################
st.set_page_config(page_title="Predicción de Cloro", layout="wide")
st.title(" Predicción de Cloro Residual")
st.markdown("Sube tu archivo CSV con columnas: `FECHA`")

archivo = st.file_uploader("📂 Carga tu archivo (CSV o Excel)", type=["csv", "xlsx"])

if archivo is not None:
    # Detectar formato por extensión
    extension = archivo.name.split('.')[-1].lower()
    df = None

    if extension == 'csv':
        # Intentar con varias codificaciones para CSV
        encodings = ['utf-8-sig', 'utf-8', 'latin-1', 'cp1252']
        for enc in encodings:
            try:
                archivo.seek(0)
                df = pd.read_csv(archivo, encoding=enc, sep=None, engine='python')
                break
            except (UnicodeDecodeError, pd.errors.ParserError):
                continue
        if df is None:
            st.error("No se pudo leer el archivo CSV. Verifica que sea un CSV válido.")
            st.stop()

    elif extension == 'xlsx':
        try:
            archivo.seek(0)
            # Leer Excel con openpyxl (requiere instalar: pip install openpyxl)
            df = pd.read_excel(archivo, engine='openpyxl')
        except Exception as e:
            st.error(f"Error al leer el archivo Excel: {e}")
            st.stop()
    else:
        st.error("Formato no soportado. Sube un archivo .csv o .xlsx")
        st.stop()

    # Normalizar nombres de columnas a MAYÚSCULAS para que coincidan con el resto del código
    df.columns = [col.upper() for col in df.columns]

    # Verificar que existan las columnas necesarias
    if 'FECHA' not in df.columns or 'CLORO' not in df.columns:
        st.error("El archivo debe contener las columnas 'FECHA' y 'CLORO' (en mayúsculas o minúsculas).")
        st.stop()

    st.subheader("Vista previa de los datos")
    st.dataframe(df.head())
    col1, col2 = st.columns(2)
    with col1:
        test_size = st.slider("Proporción de prueba (datos más recientes)", 0.1, 0.4, 0.2, 0.05)
    with col2:
        if st.button("Ejecutar Análisis", type="primary"):
            with st.spinner("Entrenando modelo y generando predicciones..."):
                resultados = ejecutar_analisis(df, test_size=test_size)

            if resultados:
                st.success("Análisis completado ;)")

                # Métricas
                m1, m2, m3 = st.columns(3)
                m1.metric("RMSE", f"{resultados['metricas']['RMSE']:.4f}")
                m2.metric("MAE", f"{resultados['metricas']['MAE']:.4f}")
                m3.metric("R²", f"{resultados['metricas']['R2']:.4f}")

                # Gráfico
                st.subheader("Comparación: Real vs Predicción")
                st.pyplot(resultados['figura'])

                #Guardar figura como JPG
                buf_jpg = io.BytesIO()
                resultados['figura'].savefig(
                    buf_jpg, format='jpg', dpi=300, bbox_inches='tight'
                )
                buf_jpg.seek(0)

                # Botón de descarga
                st.download_button(
                    label=" Descargar gráfica (.jpg)",
                    data=buf_jpg,
                    file_name="grafica_cloro.jpg",
                    mime="image/jpeg"
                )


                # Descarga del modelo (opcional)
                st.download_button(
                    label=" Descargar modelo entrenado (.pkl)",
                    data=pickle.dumps(resultados['modelo']),
                    file_name="modelo_cloro.pkl",
                    mime="application/octet-stream"
                )